// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSrLXJMIz5WipZon4O91n-dN_uANU_bA',
    appId: '1:713198259814:web:451919e9b7398e5484a7a7',
    messagingSenderId: '713198259814',
    projectId: 'desafiomobile-6da08',
    authDomain: 'desafiomobile-6da08.firebaseapp.com',
    storageBucket: 'desafiomobile-6da08.appspot.com',
    measurementId: 'G-NG0ZL32796',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPrwrc8e1NMfUcUsprrPg3ZFxTXlPeFEM',
    appId: '1:713198259814:android:b6a6a7b5c548459984a7a7',
    messagingSenderId: '713198259814',
    projectId: 'desafiomobile-6da08',
    storageBucket: 'desafiomobile-6da08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbAYO_w-zqiK9O5rPR9K-saBZHxQ4zZI0',
    appId: '1:713198259814:ios:06d2774ff4ef96ea84a7a7',
    messagingSenderId: '713198259814',
    projectId: 'desafiomobile-6da08',
    storageBucket: 'desafiomobile-6da08.appspot.com',
    iosClientId: '713198259814-5i1nf8ljec0m0cps03df3nprlc392t85.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbAYO_w-zqiK9O5rPR9K-saBZHxQ4zZI0',
    appId: '1:713198259814:ios:06d2774ff4ef96ea84a7a7',
    messagingSenderId: '713198259814',
    projectId: 'desafiomobile-6da08',
    storageBucket: 'desafiomobile-6da08.appspot.com',
    iosClientId: '713198259814-5i1nf8ljec0m0cps03df3nprlc392t85.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafioMobile',
  );
}
